### ISSUE TITLE
sync releases="[]" -> panic

### ISSUE THREAD

**Issue by zhilyaev** [zhilyaev/helmwave#31]
**Describe the bug**
releases="[]" sync release - panic

** General info (please complete the following information):**
 - OS: linux, alpine
 - Helmwave version 0.5.0

**To Reproduce**

```
project: m
version: 0.4.0
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
.options: &options
  install: true
  wait: true
  force: false
  timeout: 5m
  atomic: false
  maxhistory: 10
  namespace: dev-devops-53
releases:
  - name: postgresql
    chart: bitnami/postgresql
    options:
      <<: *options
      chartpathoptions:
        version: 8.6.13
    tags:
      - postgresql
      - infrastructure
      - adm-backend-prepare
      - prod-backend-prepare
    values:
      # a svc & all envs
      - values/infrastructure/postgresql/_.yml
      # a svc & an env
      - values/infrastructure/postgresql/dev.yml
```

helmwave deploy -t item-that-doesnt-exist

<img width="831" alt="изображение" src="https://user-images.githubusercontent.com/4854707/103280130-a84c3280-49e0-11eb-928e-d63333897341.png">

**Expected behavior**
skip
