### ISSUE TITLE
Add releases dependency graph

### ISSUE THREAD

**Issue by r3nic1e** [zhilyaev/helmwave#60]
Allow release to depend on another release

**Comment by zhilyaev** [comment]
I have thought about it. 

The easiest way is to add stages like gitlab-ci.

```yaml
releases:
  - name: first
    stage: 1

releases:
  - name: second
    stage: 2
```

or 

```yaml

stage:
  - a
  - b

releases:
  - name: first
    stage: a

releases:
  - name: second
    stage: b
```
